version: '3'
services:

  nginx:
    container_name: nextcloud_nginx
    hostname: nginx
    image: nginx:alpine
    ports:
      - 800:80
      - 8443:443
    networks:
      - cloud_net
    restart: always
    volumes:
      - ./nextcloud:/usr/share/nginx/html
      - ./nginx/conf:/etc/nginx/conf.d
      - ./ssl:/etc/certs
      - ./nginx/log:/var/log/nginx
#  db:
#    container_name: nextcloud_db
#    command:
#      --transaction-isolation=READ-COMMITTED
#      --binlog-format=ROW
#      --character-set-server=utf8mb4
#      --collation-server=utf8mb4_unicode_ci
#      --max-connections=50000
#      --max_allowed_packet=256M
#      --innodb_buffer_pool_size=256m
#      --innodb_io_capacity=4000
#    image: mariadb:10.4
#    restart: always
#    hostname: db
#    ports:
#      - 3308:3306
#    networks:
#      - cloud_net
#    volumes:
#      - ./mysql/data:/var/lib/mysql
##      - ./mysql/conf:/etc/mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_PASSWORD=nextcloud
#      - MYSQL_DATABASE=nextcloud
#      - MYSQL_USER=nextcloud

  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_DB=nextcloud
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - cloud_net
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
    expose:
      - 5432

  nextcloud_web:
#   arm64的机器 换成 scjtqs/nextcloud:arm64
    image: scjtqs/nextcloud:latest
    container_name: nextcloud_web
    hostname: nextcloud_web
    depends_on:
      - redis
      - db
    environment:
      - UID=1000
      - GID=1000
      - UPLOAD_MAX_SIZE=10G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - CRON_PERIOD=15m
      - TZ=Aisa/Shanghai
      - DOMAIN=cloud.scjtqs.com
      #      - DB_TYPE=mysql        #mysql，oci，pgsql，sqlite3
      #      - MYSQL_DATABASE=nextcloud
      #      - MYSQL_USER=root
      #      - MYSQL_PASSWORD=root
      #      - MYSQL_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_HOST=postgres
      - NEXTCLOUD_DATA_DIR=/nextcloud
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - REDIS_HOST=redis
      - REDIS_HOST_PORT=6379
      - REDIS_HOST_PASSWORD=P4ss0rd
      - NEXTCLOUD_UPDATE=1
    ports:
      - 9080:80/tcp
      #bt 穿透
      - 6801:6800
      - 51448:51448
      - 6881-6999:6881-6999
    networks:
      - cloud_net
    volumes:
      - ./nextcloud:/var/www/html
      - ./nextcloud-data/:/nextcloud
      #- ./aria2.conf:/aria2.conf

    restart: always

  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    hostname: redis
    command: --requirepass "P4ss0rd"
    restart: always
    networks:
      - cloud_net

    expose:
      - 6379


  onlyoffice:
    image: onlyoffice/documentserver
    container_name: nextcloud_onlyoffice
    hostname: onlyoffice
    environment:
      - REDIS_SERVER_HOST=redis
      - REDIS_SERVER_PORT=6379
    volumes:
      - ./onlyoffice/data:/var/www/onlyoffice/Data
      - ./onlyoffice/logs:/var/log/onlyoffice
    restart: always
    ports:
      - 9081:80/tcp
    networks:
      - cloud_net

networks:
  cloud_net:
