FROM scjtqs/nextcloud:amd64

RUN mkdir /nextcloud

COPY nextcloud-data/aria2.log /nextcloud/
COPY nextcloud-data/aria2.session /nextcloud/

RUN rm -rf /var/spool/cron/crontabs/root

RUN  echo '*/5 * * * * curl http://127.0.0.1/cron.php \r\n' >> /var/spool/cron/crontabs/root; \
            echo '*/5 * * * * cd / && bash /a2-tracker.sh \r\n' >> /var/spool/cron/crontabs/root;

COPY supervisord.kintohub.conf /

CMD ["/usr/bin/supervisord", "-c", "/supervisord.kintohub.conf"]