version: '3'
services:

  web:
    build: ./web
    restart: always
    ports:
      - 9080:80
      - 8777:8777
    networks:
      - cloud_net
    volumes:
      - ./nextcloud:/var/www/html:ro
      - ./nginx/log:/var/log/nginx
      - ./ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem    #证书
      - ./ssl/key.pem:/etc/nginx/ssl/key.pem                #证书的key文件
      - ./ssl/dhparam.pem:/etc/nginx/ssl/dhparam.pem        #请自行用 `openssl dhparam -out dhparam.pem 4096` 生成
    depends_on:
      - nextcloud_web
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

  db:
    container_name: nextcloud_db
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --sql-mode="NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    image: mysql/mysql-server:8.0
    restart: always
    ports:
      - 3308:3306
    networks:
      - cloud_net
    volumes:
      - ./mysql/data:/var/lib/mysql
    #      - ./mysql/conf:/etc/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${DATABASE_MASTER_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_MASTER_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_MASTER_DBNAME}
      MYSQL_USER: ${DATABASE_MASTER_USERNAME}
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"


#  postgres:
#    image: postgres:13-alpine
#    restart: always
#    environment:
#      - POSTGRES_PASSWORD=nextcloud
#      - POSTGRES_USER=nextcloud
#      - POSTGRES_DB=nextcloud
#    volumes:
#      - ./postgresql/data:/var/lib/postgresql/data
#    networks:
#      - cloud_net
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "1M"
#        max-file: "10"
#    expose:
#      - 5432
#
  nextcloud_web:
    image: scjtqs/nextcloud:alpine
    hostname: nextcloud_web
    depends_on:
      - redis
      - db
    environment:
      UID: 1000
      GID: 1000
      PHP_MEMORY_LIMIT: 1G
      PHP_UPLOAD_LIMIT: 10G
      TZ: Aisa/Shanghai
      NEXTCLOUD_TRUSTED_DOMAINS: "cloud.scjtqs.com 192.168.1.1"
      MYSQL_DATABASE:  ${DATABASE_MASTER_DBNAME}
      MYSQL_USER: ${DATABASE_MASTER_USERNAME}
      MYSQL_PASSWORD:  ${DATABASE_MASTER_PASSWORD}
      MYSQL_HOST: ${DATABASE_MASTER_HOST}
      #       POSTGRES_DB: nextcloud
      #       POSTGRES_USER: nextcloud
      #       POSTGRES_PASSWORD: nextcloud
      #       POSTGRES_HOST: postgres
      NEXTCLOUD_DATA_DIR: /nextcloud
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin
      REDIS_HOST: ${REDIS_HOST}
      REDIS_HOST_PORT: ${REDIS_HOST_PORT}
      REDIS_HOST_PASSWORD: ${REDIS_HOST_PASSWORD}
      NEXTCLOUD_UPDATE: 1
      SMTP_HOST: smtp.ym.163.com
      SMTP_PORT: 994
      SMTP_SECURE: ssl
      SMTP_NAME: <你的邮箱地址>
      SMTP_PASSWORD: <你的邮箱密码>
      SMTP_AUTHTYPE: LOGIN
      MAIL_FROM_ADDRESS: service
      MAIL_DOMAIN: <你的邮箱域名>
    ports:
      - 6800:6800
      - 51448:51448
      - 6881-6999:6881-6999
    networks:
      - cloud_net
    volumes:
      - ./nextcloud:/var/www/html
      - ./nextcloud-data:/nextcloud

    restart: always

  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    hostname: redis
    restart: always
    command: --requirepass "${REDIS_HOST_PASSWORD}"
    networks:
      - cloud_net
    expose:
      - 6379
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

  ## 后台地址 https://ip:9980/loleaflet/dist/admin/admin.html
  collabora:
    image: collabora/code
    restart: always
    hostname: collabora
    networks:
       - cloud_net
    ports:
      - 9980:9980
    cap_add:
      - MKNOD
    environment:
      - domain=nc.pi.scjtqs.com   #授权的域名，不能带端口
      - cert_domain=collabora.pi.scjtqs.com   #证书域名，不能带端口
      - username=admin   #管理员账号，后台登录用
      - password=P4ss0rd  #管理员密码，后台登录用
#      - extra_params=--o:ssl.enable=false  #不开启这个的话，9980端口就是https的


networks:
  cloud_net:
